### ISSUE TITLE
Getting a a struct error after writing

### ISSUE THREAD

**Issue by tunjid** [python-ivi/python-usbtmc#14]
Hello, thanks for providing such a great resource; I'm having an issue though.

In the frequency for loop, the third one, the program crashes after 85 iterations with the log provided below. This is my first Python script, so I'm not sure how to debug Python just yet. 

I've gone through the source and the issue seems to stem from the variable self.last_btag. After 85 iterations, using the functions I have the value of the variable would have been incremented (85 * 3) times = 255, hence the error.

Am I supposed to reset the value of self.last_btag somewhere? 

Thanks!

EDIT: Calling lcr.last_btag = 0 in the loop fixes the problem temporarily, will test latest git commit when I can.

``` Python
from time import sleep
import usbtmc
import serial

lcr = usbtmc.Instrument(2391, 2313)

Arduino = serial.Serial('/dev/tty.usbmodem1421', 38400, timeout=10)


for i in range(0, 4):
    print()
    for R1 in range(0, 64):
        # Instruct Arduino to change rheostat wiper
        Arduino.write(b'1')
        sleep(0.1)
        for f in range(0, 99):
            lcr.write(":TRIG:IMM")
            # TEMPOARY FIX: lcr.last_btag = 0
            sleep(0.1)
            data = lcr.ask("FETC:IMP:FORM?")
            sleep(0.1)
            print(str(R1) + "," + str(f) + "," + data)
```

Error Log:

```
  File "build/bdist.macosx-10.10-intel/egg/usbtmc/usbtmc.py", line 479, in write
  File "build/bdist.macosx-10.10-intel/egg/usbtmc/usbtmc.py", line 410, in write_raw
  File "build/bdist.macosx-10.10-intel/egg/usbtmc/usbtmc.py", line 359, in pack_dev_dep_msg_out_header
  File "build/bdist.macosx-10.10-intel/egg/usbtmc/usbtmc.py", line 356, in pack_bulk_out_header
struct.error: ubyte format requires 0 <= number <= 255
```

**Comment by alexforencich** [comment]
This should get reset automatically.

**Comment by alexforencich** [comment]
Please remove your last_btag fix and test with the latest git revision and let me know what happens.

**Comment by tunjid** [comment]
Unfortunately our LCR developed issues recently and I won't be able to test just yet. I will as soon as I can.

**Comment by alexforencich** [comment]
Well, this should be fixed with the latest version.  Feel free to re-open this issue if it isn't.
