### ISSUE TITLE
module can't find Oscilloscope

### ISSUE THREAD

**Issue by BBelonder** [python-ivi/python-usbtmc#30]
Hey there and thank you so much for that splendid module you've set up!

I used python-usbtmc earlier in the year to set up a piece of code to read out my oscilloscope (Tektronix TDS2000b) and it wokred just fine.
Recently I've gotten a new pair of Oscis (GW Instek GDS-1104B) and tried to get my code working with them aswell but unfortunately the usbtmc won't find my device, stating an Error like this:
" raise UsbtmcException("Device not found", 'init')"
This Error occurs no matter if hex or dec VID/PID input and no matter if python's been running with sudo or without
I've followed the instructions in the manual (groupadd and usbtmc.rules) and am running python 2.7.9/3.4.2 (either version doesn't work) on a Raspbian 4.4.34-v7 raspi.

The list when using usbtmc.list_devices() is completely empty, is that supposed to be like this?
This leads me to the feeling that the module isn't loading the .rules file correctly, is that right?

Do you have any other idea what to try/do/fix?

**Comment by alexforencich** [comment]
Are you sure the scope you're trying to interface with actually supports USBTMC?

**Comment by BBelonder** [comment]
Darn.

I figured every newer model of scopes would support that. Obviously I was mistaken. Thanks for the fast answer!

The GDS1104B doesn't seem to support usbtmc, while a tektronix scope works out of the box.

Thanks again for the module and the help!

**Comment by alexforencich** [comment]
To be honest, it's infuriating when companies go invent their own protocols instead of using standard, widely supported protocols.

**Comment by BBelonder** [comment]
Well, it's supporting USBCDC, i just gotta check if that protocol is fast enough or if I have to go aroud the institute to exchange my scope with one supporting usbtmc
