### ISSUE TITLE
usbtmc Access Denied 

### ISSUE THREAD

**Issue by macdroid53** [python-ivi/python-usbtmc#33]
Hi,
sudo usbtmc-shell --backend python_usbtmc USB::0x1ab1::0x0588::INSTR
Runs fine, without sudo I get access denied.
I added the udev rule, added group usbtmc, added usbtmc group to user.
Running Ubuntu 16.04.
I'm assuming I did something wrong... :(

**Comment by alexforencich** [comment]
Did you reload udev rules and re-plug the device?  Did you log out and log in again so the new group membership takes effect?  Or reboot?

**Comment by macdroid53** [comment]
First tried unplug/plug, then logout/login, then reboot.

**Comment by alexforencich** [comment]
OK.  What are the device permissions in /dev/bus/usb?

**Comment by macdroid53** [comment]
Permissions shown below.

But, after my last email, I unplugged, rebooted, then plugged...now
non-sudo works. :/

 ls -la /dev/bus/usb
total 0
drwxr-xr-x 4 root root  80 May 17 09:43 .
drwxr-xr-x 3 root root  60 May 17 09:43 ..
drwxr-xr-x 2 root root 180 May 17 09:47 001
drwxr-xr-x 2 root root  60 May 17 09:43 002


PS: USB::0x1ab1::0x0588::INSTR is for a Rigol DS1102D scope (I note you
have other Rigols in usbtmc.rules
<https://github.com/python-ivi/python-usbtmc/blob/master/usbtmc.rules>

**Comment by alexforencich** [comment]
I need the permissions of the device itself, not the hub.  Run lsusb to figure out what the bus number is, cd into that folder, and run ls -a there.  That should show the current owner, group, and permissions of the device.

**Comment by macdroid53** [comment]
Oh.ok its bus 1 device 7

 ls -la
total 0
drwxr-xr-x 2 root root      180 May 17 09:47 .
drwxr-xr-x 4 root root       80 May 17 09:43 ..
crw-rw-r-- 1 root root   189, 0 May 17 09:43 001
crw-rw-r-- 1 root root   189, 1 May 17 09:43 002
crw-rw-r-- 1 root root   189, 2 May 17 09:43 003
crw-rw-r-- 1 root root   189, 3 May 17 09:43 004
crw-rw-r-- 1 root root   189, 4 May 17 09:43 005
crw-rw-r-- 1 root root   189, 5 May 17 09:43 006
crw-rw---- 1 root usbtmc 189, 6 May 17 10:02 007

**Comment by alexforencich** [comment]
So the permissions on that look correct - group writeable, group set to usbtmc.  Is it still not working?

**Comment by macdroid53** [comment]
Umm...it is working.

In the previous email I noted that after unplugging, rebooting, and then
plugging,NON-sudo now works. :)

The only difference was, I plugged it in after rebooting. Not sure why that
fixed it...

**Comment by alexforencich** [comment]
Ah, I see.  Good to hear that it appears to be working now.

**Comment by macdroid53** [comment]
Sorry I didn't get it before I posted the GITHUB issue.

**Comment by alexforencich** [comment]
No worries!

**Comment by macdroid53** [comment]
Hi Alex,

Sorry to raise my hand again...

I now seem to have the scope working consistently. I.e. it's there and I
can access it all the time.

But, I can't seem to get to the second Rigol device (a DG1022).

It shows up on lsusb:

lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 046d:c52f Logitech, Inc. Unifying Receiver
Bus 001 Device 014: ID 1ab1:0588 Rigol Technologies DS1000 SERIES
Bus 001 Device 003: ID 2001:f103 D-Link Corp. DUB-H7 7-port USB 2.0 hub
Bus 001 Device 002: ID 1c7a:0603 LighTuning Technology Inc.
Bus 001 Device 008: ID 8087:0a2a Intel Corp.
Bus 001 Device 006: ID 5986:066d Acer, Inc
Bus 001 Device 016: ID 0400:09c4 National Semiconductor Corp. Rigol
Technologies DG1022 Arbitrary Waveform Generator
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Even from code:

import usbtmc
print(usbtmc.list_devices())

produces:
import usbtmc
print(usbtmc.list_devices())

But:
# open scope
oscope =  usbtmc.Instrument(0x1ab1, 0x0588)
print(oscope.ask("*IDN?"))
# initial settings

# open Function generator
funcgen =  usbtmc.Instrument(0x0400, 0x09c4)
print(funcgen.ask("*IDN?"))

produces:
Traceback (most recent call last):
  File "/home/mac/SharedData/PycharmProjs/RigolScope/ResponseMeasure.py",
line 24, in <module>
    print(funcgen.ask("*IDN?"))
  File "/usr/local/lib/python3.5/dist-packages/usbtmc/usbtmc.py", line
753, in ask
    self.write(message, encoding)
  File "/usr/local/lib/python3.5/dist-packages/usbtmc/usbtmc.py", line
733, in write
    self.write_raw(str(message).encode(encoding))
  File "/usr/local/lib/python3.5/dist-packages/usbtmc/usbtmc.py", line
599, in write_raw
    self.open()
  File "/usr/local/lib/python3.5/dist-packages/usbtmc/usbtmc.py", line
434, in open
    self.device.set_configuration(self.cfg)
  File "/usr/local/lib/python3.5/dist-packages/usb/core.py", line 869,
in set_configuration
    self._ctx.managed_set_configuration(self, configuration)
  File "/usr/local/lib/python3.5/dist-packages/usb/core.py", line 102,
in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/usb/core.py", line 147,
in managed_set_configuration
    self.managed_open()
  File "/usr/local/lib/python3.5/dist-packages/usb/core.py", line 102,
in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/usb/core.py", line 120,
in managed_open
    self.handle = self.backend.open_device(self.dev)
  File "/usr/local/lib/python3.5/dist-packages/usb/backend/libusb1.py",
line 786, in open_device
    return _DeviceHandle(dev)
  File "/usr/local/lib/python3.5/dist-packages/usb/backend/libusb1.py",
line 643, in __init__
    _check(_lib.libusb_open(self.devid, byref(self.handle)))
  File "/usr/local/lib/python3.5/dist-packages/usb/backend/libusb1.py",
line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)

But, the bus doesn't have the usbtmc group (see #16):

/dev/bus/usb/001$ ls -la
total 0
drwxr-xr-x 2 root root       200 May 22 19:11 .
drwxr-xr-x 4 root root        80 May 22 18:30 ..
crw-rw-r-- 1 root root   189,  0 May 22 18:53 001
crw-rw-r-- 1 root root   189,  1 May 22 18:53 002
crw-rw-r-- 1 root root   189,  2 May 22 18:53 003
crw-rw-r-- 1 root root   189,  3 May 22 18:53 004
crw-rw-r-- 1 root root   189,  5 May 22 18:53 006
crw-rw-r-- 1 root root   189,  7 May 22 18:53 008
crw-rw---- 1 root usbtmc 189, 13 May 22 19:07 014
crw-rw-r-- 1 root root   189, 15 May 22 19:11 016

This is what I put in the rules file:

# USBTMC instruments

# Rigol DS1120D
SUBSYSTEMS=="usb", ACTION=="add", ATTRS{idVendor}=="1ab1",
ATTRS{idProduct}=="0588", GROUP="usbtmc", MODE="0660"
SUBSYSTEMS=="usb", ACTION=="add", ATTRS{idVendor}=="0400",
ATTRS{idProduct}=="09C4", GROUP="usbtmc", MODE="0660"
# Devices
KERNEL=="usbtmc/*",       MODE="0660", GROUP="usbtmc"
KERNEL=="usbtmc[0-9]*",   MODE="0660", GROUP="usbtmc"

Any ideas?

Thanks,

Mac

**Comment by alexforencich** [comment]
idVendor and idProduct are case-sensitive, I think.

**Comment by macdroid53** [comment]
hmm...Ok, I'll change that and try again sometime tomorrow.

**Comment by macdroid53** [comment]
Good morning.

I fixed the case in the udev rule and it behaves now when plugging in and
the access error is gone.

But, when I access the instrument, it times out. The device shows that it
goes into remote mode on its display, does not respond to the *IDN?.

Pertinent parts of code:

import usbtmc
print(usbtmc.list_devices())
# open scope
oscope =  usbtmc.Instrument(0x1ab1, 0x0588)
print(oscope.ask("*IDN?"))
# initial settings

# open Function generator
funcgen =  usbtmc.Instrument(0x0400, 0x09c4)
print(funcgen.ask("*IDN?"))

Output:

[<DEVICE ID 1ab1:0588 on Bus 001 Address 007>, <DEVICE ID 0400:09c4 on Bus
001 Address 008>]
Rigol Technologies,DS1102D,DS1EA113100571,00.04.02.01.00
Traceback (most recent call last):
  File "/home/mac/SharedData/PycharmProjs/RigolScope/ResponseMeasure.py",
line 24, in <module>
    print(funcgen.ask("*IDN?"))
  File "/usr/local/lib/python3.5/dist-packages/usbtmc/usbtmc.py", line 754,
in ask
    return self.read(num, encoding)
  File "/usr/local/lib/python3.5/dist-packages/usbtmc/usbtmc.py", line 737,
in read
    return self.read_raw(num).decode(encoding).rstrip('\r\n')
  File "/usr/local/lib/python3.5/dist-packages/usbtmc/usbtmc.py", line 656,
in read_raw
    resp = self.bulk_in_ep.read(read_len+USBTMC_HEADER_SIZE+3,
timeout=self._timeout_ms)
  File "/usr/local/lib/python3.5/dist-packages/usb/core.py", line 402, in
read
    return self.device.read(self, size_or_buffer, timeout)
  File "/usr/local/lib/python3.5/dist-packages/usb/core.py", line 988, in
read
    self.__get_timeout(timeout))
  File "/usr/local/lib/python3.5/dist-packages/usb/backend/libusb1.py",
line 833, in bulk_read
    timeout)
  File "/usr/local/lib/python3.5/dist-packages/usb/backend/libusb1.py",
line 936, in __read
    _check(retval)
  File "/usr/local/lib/python3.5/dist-packages/usb/backend/libusb1.py",
line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 110] Operation timed out

Note: same error when this is typed in a terminal:
usbtmc-shell --backend python_usbtmc USB::0x0400::0x09c4::INSTR

**Comment by alexforencich** [comment]
Rigol instruments do not currently implement standards-compliant USBTMC, and they reuse PIDs across many instruments, making it infeasible to reverse-engineer and implement instrument-specific quirks, as each instrument seems to screw up the implementation in different ways.  I would recommend using an alternative remote interface, if possible.  Their ethernet interfaces seem to have fewer bugs.

**Comment by macdroid53** [comment]
Unfortunately, the DG1022 has only usb. :(

Oh, well, maybe I'll try sending various thnings and see if I can figure it
out...

Thanks for all the elp though!

Mac

**Comment by alexforencich** [comment]
Yeah, I'm not sure what the issue would be, but it won't be with the syntax of the command, it will be in how the underlying protocol works.  So that would mean going and digging around in usbtmc.py.  Unforunately, this is a rather difficult issue to work out as there isn't much feedback beyond the command timing out.  Probably the only way to make it work would be to capture instrument communication with the rigol provided driver with wireshark and then figure out what it is that the instrument wants to see.  However, it's supposed to be USBTMC, and the driver I have follows the USBTMC spec, so the really correct solution is to yell at Rigol until they release a new firmware that actually implements USBTMC correctly.

**Comment by macdroid53** [comment]
Hi Alex,

So, I messed with the Rigol function generator some, but basically its a
lost cause. They have a new model, so aren't very interested in fixing the
older.

I have now been looking at the Rigol DS1102D that I have. It appears to
work as long as the program is running. If I attempt to run again, it times
out on any function. But if I unplug the usb and re-plug the program runs
again.

Would you guess this is the Rigol quirk is see handled in usbtmc.py or some
other usb issue? THe re-plug makes me think the connection is just not
being closed correctly, even though I do call the usbtmc close().

Regards,Mac
