### ISSUE TITLE
FreeBSD problem with reset

### ISSUE THREAD

**Issue by uffejakobsen** [python-ivi/python-usbtmc#9]
Hi,

On FreeBSD the reset issued during connect is no good - and prevents usctmc from working (throws exception). If I remove/disable the exception is works fine.

I suspect that you've has/seen the same problem with eg Windows ?
At lease I can see that usbtmc.py line 255 has the following construction:

if os.name == 'posix':
            self.device.reset()

That needs to be extended to specificly check for FreeBSD (using os.platform or os.uname ???)

Please let me know if you need more info
/Uffe

**Comment by alexforencich** [comment]
This particular reset call has now been completely removed, so this should no longer be an issue.
